FROM python:3.10-alpine as builder

WORKDIR /backend

COPY requirements.txt  .

RUN pip install --no-cache-dir -r requirements.txt

FROM python:3.10-alpine

WORKDIR /backend 

COPY --from=builder /usr/local/lib/python3.10/site-packages/ /usr/local/lib/python3.10/site-packages/

COPY . . 

EXPOSE 5000

CMD ["python","app.py"]
