FROM node:21-alpine3.18 as builder

WORKDIR /backend

COPY package*.json /backend/

RUN npm install 

FROM alpine:3.14

WORKDIR /backend

COPY --from=builder /backend .

EXPOSE 3000

CMD ["node","app.js"]
