FROM golang:1.20 as builder

WORKDIR /backend

COPY . .

RUN go mod download

RUN go build -o main .

FROM alpine:3.14

WORKDIR /backend

COPY --from=builder /backend/main .

EXPOSE 8080

CMD ["./main"]
